### ISSUE TITLE
Integrate Travis CI for SonarQuest

### ISSUE THREAD

**Issue by fkoehne** [viadee/sonarQuest#6]

**Comment by fkoehne** [comment]
Travis should be active on the next push.

**Comment by TamaraGunkel** [comment]
You still have to activate the repository on Travis CI.

**Comment by fkoehne** [comment]
Done. :)

**Comment by fkoehne** [comment]
Travis tries to build the root-directory, not the backend. @TamaraGunkel, can you please take a look?

**Comment by TamaraGunkel** [comment]
Done!

**Comment by fkoehne** [comment]
Great! It seems we need @h-huss' startup parameter next?
`http://localhost:3000/projects": Connection refused (Connection refused)`

**Comment by h-huss** [comment]
Yes, its already used for `SonarQuestApplicationIT`, but for `UserManagementIT` `@SpringBootTest` needs to be replaced with `@SpringBootTest(properties = "simulateSonarServer=true")`

**Comment by h-huss** [comment]
The build still fails, but for a different reason: `SonarQuestApplicationIT` expects special mocking data instead of the simulated data. 

The test can either be rewritten to expect the simulated data, or the mock has to be made availible to the complete DI framework so the server startup uses it too.

**Comment by TamaraGunkel** [comment]
I have done this already

**Comment by fkoehne** [comment]
:)

**Comment by fkoehne** [comment]
:)
